# Generated by Django 2.2.4 on 2019-09-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
