# Generated by Django 2.2.4 on 2019-09-14 09:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=users.models.user_photo_path, validators=[users.models.user_photo_size_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, upload_to=users.models.user_photo_path),
        ),
    ]
