# Generated by Django 2.2.4 on 2019-08-25 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('to', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together={('to', 'user')},
        ),
    ]
