# Generated by Django 2.2.4 on 2019-09-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190902_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervote',
            old_name='type',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='type',
            new_name='value',
        ),
    ]
