# Generated by Django 2.2.4 on 2019-09-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20190905_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', related_query_name='votes', to='questions.Answer'),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', related_query_name='votes', to='questions.Question'),
        ),
    ]
