# Generated by Django 2.2.4 on 2019-09-07 13:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190907_0958'),
    ]

    operations = []  # type: ignore
